apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example
  description: example.com
  annotations:
    gitlab.com/project-id: '60213724'  # Replace with your actual GitLab Project ID  # Replace with your actual GitLab Project Slug
spec:
  type: service



